name: Update Readme Documentation

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  updates_readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Detect Changes
      id: changes
      run: |
        git fetch origin master
        if [ $(git rev-list --count HEAD) -eq 1 ]; then
          echo "Initial commit detected. No changes to compare."
          exit 0
        fi
        git diff --name-only origin/master HEAD > changed_files.txt

    - name: Install Dependencies
      run: |
        pip install google-generativeai python-dotenv

    - name: Update Readme
      env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      run: |
        python update_readme.py --changed-files changed_files.txt

    - name: Commit and Push Changes
      run: |
        git config user.name "Grokr-gyanendra"
        git config user.email "gyanendra.shukla@datagrokr.co"
        git add README.md
        git commit -m "Automated update to README.md" || echo "No changes to commit."
        git push
